name: main

on:
  merge_group:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main
      - release/*

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "21.0.0"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: npm install
        run: npm ci

      - name: build frontend
        run: npm run build

      - name: run npm unit tests
        run: npm run test:unit

      - name: install browsers
        run: npx playwright install

      - name: run npm tests
        run: npm test

      - name: archive screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-screenshots
          path: screenshots

      - name: Showing difference
        run: git --no-pager diff
      - name: Checking for differences
        run: git diff-index --exit-code HEAD --

