name: main

on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main
      - release/*

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD'
          abbrev: false
          skip-unshallow: true

      - name: Show Tag
        id: display
        run: | 
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'

      - uses: actions/setup-node@v3
        with:
          node-version: "current"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: npm install
        run: npm ci


      - name: build frontend
        run: npm run build

      - name: run npm unit tests
        run: npm run test:unit

      - name: install browsers
        run: npx playwright install

      - name: run npm tests
        run: npm test

      - name: archive screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-screenshots
          path: screenshots
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/kokabieli/kokabieli-ui:${{ steps.tagger.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Showing difference
        run: git --no-pager diff
      - name: Checking for differences
        run: git diff-index --exit-code HEAD --

